var searchData=
[
  ['object_20categorization',['Object Categorization',['../group__features2d__category.html',1,'']]],
  ['opengl_20support',['OpenGL support',['../group__highgui__opengl.html',1,'']]],
  ['object_20detection',['Object Detection',['../group__imgproc__object.html',1,'']]],
  ['object_20detection',['Object Detection',['../group__objdetect.html',1,'']]],
  ['ocr_5fdecoder_5fviterbi',['OCR_DECODER_VITERBI',['../group__text__recognize.html#gac1843f0d2e0e7136debaa46d45446b11',1,'org::bytedeco::javacpp::opencv_text']]],
  ['ocr_5flevel_5fword',['OCR_LEVEL_WORD',['../group__text__recognize.html#gac4148e33328b79dbead3c33dac186540',1,'org::bytedeco::javacpp::opencv_text']]],
  ['opencv_5fbioinspired',['opencv_bioinspired',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__bioinspired.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fbioinspired_2ejava',['opencv_bioinspired.java',['../opencv__bioinspired_8java.html',1,'']]],
  ['opencv_5fcalib3d',['opencv_calib3d',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__calib3d.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fdnn',['opencv_dnn',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__dnn.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fface',['opencv_face',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__face.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5ffeatures2d',['opencv_features2d',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__features2d.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fflann',['opencv_flann',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__flann.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fhighgui',['opencv_highgui',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__highgui.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fimgcodecs',['opencv_imgcodecs',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__imgcodecs.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fimgproc',['opencv_imgproc',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__imgproc.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fml',['opencv_ml',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__ml.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fobjdetect',['opencv_objdetect',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__objdetect.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5foptflow',['opencv_optflow',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__optflow.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fphoto',['opencv_photo',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__photo.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fshape',['opencv_shape',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__shape.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fstitching',['opencv_stitching',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__stitching.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fsuperres',['opencv_superres',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__superres.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5ftext',['opencv_text',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__text.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fvideo',['opencv_video',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__video.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fvideoio',['opencv_videoio',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__videoio.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fvideostab',['opencv_videostab',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__videostab.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fxfeatures2d',['opencv_xfeatures2d',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__xfeatures2d.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fximgproc',['opencv_ximgproc',['../classorg_1_1bytedeco_1_1javacpp_1_1opencv__ximgproc.html',1,'org::bytedeco::javacpp']]],
  ['opencv_5fximgproc_2ejava',['opencv_ximgproc.java',['../opencv__ximgproc_8java.html',1,'']]],
  ['optical_20flow_20algorithms',['Optical Flow Algorithms',['../group__optflow.html',1,'']]],
  ['optflow_5fuse_5finitial_5fflow',['OPTFLOW_USE_INITIAL_FLOW',['../group__video__track.html#ga7544170e893b4e8835522881418d396d',1,'org::bytedeco::javacpp::opencv_video']]],
  ['object_20tracking',['Object Tracking',['../group__video__track.html',1,'']]]
];
