var searchData=
[
  ['pencilsketch',['pencilSketch',['../group__photo__render.html#gafec8b96cb1b707bb2a5b2b2d3957f92d',1,'org::bytedeco::javacpp::opencv_photo']]],
  ['phasecorrelate',['phaseCorrelate',['../group__imgproc__motion.html#gaa6db080ff5a1fc47bf09771158c47abb',1,'org::bytedeco::javacpp::opencv_imgproc']]],
  ['pointpolygontest',['pointPolygonTest',['../group__imgproc__shape.html#gaf6f02003be04d7a37eff3af25946ff77',1,'org::bytedeco::javacpp::opencv_imgproc']]],
  ['polylines',['polylines',['../group__imgproc__draw.html#ga12a242d17a2019ba1318b61c43b54c75',1,'org.bytedeco.javacpp.opencv_imgproc.polylines(@ByRef Mat img, @Cast(&quot;const cv::Point*const*&quot;) PointerPointer pts, @Const IntPointer npts, int ncontours, @Cast(&quot;bool&quot;) boolean isClosed, @Const @ByRef Scalar color, int thickness, int lineType, int shift)'],['../group__imgproc__draw.html#ga00ed857a005204839489574ac441f9c6',1,'org.bytedeco.javacpp.opencv_imgproc.polylines(@ByVal Mat img, @ByVal MatVector pts, @Cast(&quot;bool&quot;) boolean isClosed, @Const @ByRef Scalar color, int thickness, int lineType, int shift)']]],
  ['pos',['pos',['../group__imgproc.html#ga2eeb5802ad1e50df4b7d2fee4ec99f19',1,'org::bytedeco::javacpp::opencv_imgproc::LineIterator']]],
  ['precornerdetect',['preCornerDetect',['../group__imgproc__feature.html#ga1c51e6cab3684b202f45967edc555f5c',1,'org::bytedeco::javacpp::opencv_imgproc']]],
  ['prev_5felem',['prev_elem',['../group__imgproc.html#ga291c319aa2e16f48fced0c98b62516d3',1,'org::bytedeco::javacpp::opencv_imgproc::CvChainPtReader']]],
  ['projectpoints',['projectPoints',['../group__calib3d.html#gaa19528257b52c058dffc58aba4f6d751',1,'org.bytedeco.javacpp.opencv_calib3d.projectPoints( @ByVal Mat objectPoints, @ByVal Mat rvec, @ByVal Mat tvec, @ByVal Mat cameraMatrix, @ByVal Mat distCoeffs, @ByVal Mat imagePoints, @ByVal(nullValue=&quot;cv::OutputArray(cv::noArray())&quot;) Mat jacobian, double aspectRatio)'],['../group__calib3d__fisheye.html#gaf2fa76c626de207fce922dd3c2a1defc',1,'org.bytedeco.javacpp.opencv_calib3d.projectPoints(@ByVal Mat objectPoints, @ByVal Mat imagePoints, @Const @ByRef Mat affine, @ByVal Mat K, @ByVal Mat D, double alpha, @ByVal(nullValue=&quot;cv::OutputArray(cv::noArray())&quot;) Mat jacobian)'],['../group__calib3d__fisheye.html#ga01c2fc60a861f2b9972e00c4837a315b',1,'org.bytedeco.javacpp.opencv_calib3d.projectPoints(@ByVal Mat objectPoints, @ByVal Mat imagePoints, @ByVal Mat rvec, @ByVal Mat tvec, @ByVal Mat K, @ByVal Mat D, double alpha, @ByVal(nullValue=&quot;cv::OutputArray(cv::noArray())&quot;) Mat jacobian)']]],
  ['ptr',['ptr',['../group__imgproc.html#ga985f30fcc54d909935454e69374f4f7b',1,'org::bytedeco::javacpp::opencv_imgproc::CvChainPtReader']]],
  ['puttext',['putText',['../group__imgproc__draw.html#ga18902c6aaf4382fce2c9c0097906f49c',1,'org::bytedeco::javacpp::opencv_imgproc']]],
  ['pyrup',['pyrUp',['../group__imgproc__filter.html#ga3fc37612b218d8cee2f4b099a8d0a2aa',1,'org::bytedeco::javacpp::opencv_imgproc']]]
];
